### ISSUE TITLE
Unable to find electron app in repo dir

### ISSUE THREAD

**Issue by code-hunger** [doreminiature/miniature#2]
After `npm i` I run `electron .` and got this:

```
Error launching app
Unable to find Electron app at /home/user/doremi
Cannot find module '/home/user/doremi
```
`grunt linuxBuild` says this:
```
Running "concat:browser" (concat) task
                                                                                                                                      
Done.
```
But there is nothing in `dist/` except for a `build.js`.  
This happens on ArchLinux.

**Comment by doreminiature** [comment]
Do you have electron installed globally?

**Comment by code-hunger** [comment]
Of course I do... If I didn't I wouldn't be able to run `electron .` anyway - I'd get "command not found" or something.

**Comment by doreminiature** [comment]
Ok, I too had problems building dist last evening, but I have managed to fix problem. I'm going to push updates soon. Btw today we are going to release first version (alpha) of the product.

**Comment by doreminiature** [comment]
I completely forgot about this issue. @code-hunger can you check if it builds now? Try to build from master branch.

**Comment by code-hunger** [comment]
`grunt linuxBuild` runs fine; `electron .` still gives the same error:
```
Error launching app
Unable to find Electron app at /home/user/doremi
Cannot find module '/home/user/doremi
```

**Comment by doreminiature** [comment]
can you check if Run: `/Path/To/Electron` `/Path/To/Miniature` works for you?

**Comment by code-hunger** [comment]
I already posted this in my previous answer; sorry but I forgot to mention that I run `electron .` in the miniature folder so it's essentially the same as what you suggested.

**Comment by doreminiature** [comment]
@code-hunger can you try to build from latest master, please?

**Comment by code-hunger** [comment]
`grunt linuxBuild` says `Done` and exits successfully.

`electron .` still gives the same error, even after `grunt linuxBuild`. Using Electron v1.6.11.

I ran both commands after `npm i`.

**Comment by doreminiature** [comment]
In case of Min, "electron ." goes fine there?

**Comment by code-hunger** [comment]
Yes. Perhaps we have different node configurations which cause miss-generation of some package-files (I'm not very familiar with these tools)?

Here's the full contents of the repo folder, hopefully it'll give some hints:

> css   ext   .gitignore    icon.icns  img         js           main          .nvmrc        package-lock.json  pdfjs   README.md                      
> dist  .git  Gruntfile.js  icons      index.html  LICENSE.txt  node_modules  package.json  pages              reader
>

**Comment by doreminiature** [comment]
@code-hunger 
I just tried this on ubuntu 17.04: 
```
$ npm install --save-dev electron
# Launch from inside your project's directory:
$ ./node_modules/.bin/electron .
```
It is from electron [releases](https://electron.atom.io/releases/) page.
And it works. Can you check if it works for you?

**Comment by code-hunger** [comment]
No... It's essentially the same, only difference is that electron was installed locally to the repo.

I'll try now `git-clone` anew, hope it'll work this time.

**Comment by code-hunger** [comment]
`electron .` didn't work until I ran (unsuccessfully) `grunt linuxBuild`. Here's the relevant part:

```
Running "electron:linuxBuild" (electron) task                                                                                                        
WARNING: The version parameter is deprecated, use electronVersion (or --electron-version in the CLI) instead                                         
WARNING: The app-version parameter is deprecated when used from JS, use appVersion instead. It will be removed in the next major version.            
Downloading tmp-6365-1-SHASUMS256.txt-1.7.9
[============================================>] 100.0% of 2.93 kB (2.93 kB/s)
Downloading tmp-6365-2-electron-v1.7.9-linux-armv7l.zip
[============================================>] 100.0% of 44.77 MB (72.98 kB/s)
Packaging app for platform linux armv7l using electron v1.7.9                                                                                        
                                                                                                                                                     
Running "electron-installer-debian:linux32" (electron-installer-debian) task                                                                         
Creating package (this may take a while)
>> Error creating package: Error executing command (127): 
>> fakeroot dpkg-deb --build /tmp/electron-117922-6365-1u4y146.c6nbl/miniature_0.0.0_i386
>> /usr/bin/fakeroot: line 178: dpkg-deb: command not found
Warning: Error executing command (127): 
fakeroot dpkg-deb --build /tmp/electron-117922-6365-1u4y146.c6nbl/miniature_0.0.0_i386
/usr/bin/fakeroot: line 178: dpkg-deb: command not found
 Use --force to continue.

Aborted due to warnings.
```

I do not understand what is all that `debian` stuff as I'm running archlinux, but it's a fact that after this ^^ miniature started successfully.

And btw, I like the updated readme :) but you should reorder the steps: *"Run electron"* should go *after* `grunt *Build`.

**Comment by doreminiature** [comment]
Great! Finally closing this issue. Happy days!
