### ISSUE TITLE
Any plan for applying khan/aphrodite?

### ISSUE THREAD

**Issue by luixxiul** [doreminiature/miniature#6]
Hi there,

I am just wondering if you are planning to adopt https://github.com/Khan/aphrodite to replace external css/ with inlined styles to maintain style consistency, to render faster, etc.

Recently I have been working on [Aphrodite conversion project for Brave browser](https://github.com/brave/browser-laptop/projects/7) and [a documentation](https://github.com/brave/browser-laptop/blob/master/docs/style.md). I am not familiar with either React nor Webcomponent, but with CSS and BEM adoption. If you have a plan to do so, it would be appreciated if you ping me. I'd love to help.

**Comment by lucat1** [comment]
Cool! Indeed we're going to rewrite the browser with Inferno(react-like library) and we're going to use a CSS-in-JS solution. Currently, [this](https://github.com/slupjs/slup/tree/rewrite/packages/Theming/src) is what I've built for the UI framework I've built of the browser. If you'd like to help us with our projects you can join [our gitter](https://gitter.im/miniature-web/Lobby) chat or ping me on discord at `LucaT#7910`

Any help would be appreciated. Even discussions about the UI❤️

BTW you did an amazing job for the Brave browser!! That's amazing! 😍
